ALTER TABLE COMP1 ALTER COLUMN OCOMPID INT NULL
GO
ALTER TABLE COMP2 ADD CustID decimal(18,0) NULL
GO
ALTER TABLE COMP2 ALTER COLUMN OCOMPID INT NULL
GO
ALTER TABLE OQUES ADD Mandatory BIT NULL
GO
UPDATE OQUES SET Mandatory =0
GO
ALTER TABLE OQUES ALTER COLUMN Mandatory BIT NOT NULL
GO
ALTER TABLE OCLM ADD UnitID INT NULL
GO
ALTER TABLE CLM1 ADD UnitID INT NULL
GO
ALTER TABLE OCOMP ADD BrandID nvarchar(50) NOT NULL
GO
Alter Table TOCRD Add DeletedBy int
GO
Alter Table TOCRD Add DeletedDate Datetime
GO

ALTER TABLE SCM1 ADD SAPCREATEDBY NVARCHAR(25)
ALTER TABLE SCM1 ADD SAPCREATEDDATE DATETIME
ALTER TABLE SCM1 ADD SAPCHANGEBY NVARCHAR(25)
ALTER TABLE SCM1 ADD SAPCHANGEDATE DATETIME
ALTER TABLE SCM1 ADD SAPSYNCUSER NVARCHAR(25)

ALTER TABLE orut
  ADD  RouteType int;
UPDATE ORUT SET RouteType = 3 
ALTER TABLE orut
  ALTER COLUMN RouteType int NOT NULL;