ALTER TABLE [dbo].[RUT1] DROP CONSTRAINT [FK_RUT1_ORUT]
GO

ALTER TABLE [dbo].[RUT1] DROP CONSTRAINT [FK_RUT1_OCRD]
GO

ALTER TABLE [dbo].[RUT1] DROP CONSTRAINT [FK_RUT1_CRD1]
GO

ALTER TABLE [dbo].[RUT1] DROP CONSTRAINT [DF__RUT1__IsDeleted__79C80F94]
GO

ALTER TABLE [dbo].[RUT1] DROP CONSTRAINT [DF_RUT1_Active]
GO

/****** Object:  Table [dbo].[RUT1]    Script Date: 04-08-2017 14:47:06 ******/
DROP TABLE [dbo].[RUT1]
GO

/****** Object:  Table [dbo].[RUT1]    Script Date: 04-08-2017 14:47:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RUT1](
	[RUT1ID] [int] NOT NULL,
	[ParentID] [numeric](18, 0) NOT NULL,
	[RouteID] [int] NOT NULL,
	[CustomerID] [numeric](18, 0) NOT NULL,
	[BranchID] [int] NOT NULL,
	[Active] [bit] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_RUT1] PRIMARY KEY CLUSTERED 
(
	[RUT1ID] ASC,
	[ParentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[RUT1] ADD  CONSTRAINT [DF_RUT1_Active]  DEFAULT ((0)) FOR [Active]
GO

ALTER TABLE [dbo].[RUT1] ADD  CONSTRAINT [DF_RUT1_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO

ALTER TABLE [dbo].[RUT1]  WITH CHECK ADD  CONSTRAINT [FK_RUT1_CRD1] FOREIGN KEY([BranchID], [CustomerID])
REFERENCES [dbo].[CRD1] ([BranchID], [CustomerID])
GO

ALTER TABLE [dbo].[RUT1] CHECK CONSTRAINT [FK_RUT1_CRD1]
GO

ALTER TABLE [dbo].[RUT1]  WITH NOCHECK ADD  CONSTRAINT [FK_RUT1_OCRD] FOREIGN KEY([CustomerID])
REFERENCES [dbo].[OCRD] ([CustomerID])
GO

ALTER TABLE [dbo].[RUT1] CHECK CONSTRAINT [FK_RUT1_OCRD]
GO

ALTER TABLE [dbo].[RUT1]  WITH NOCHECK ADD  CONSTRAINT [FK_RUT1_ORUT] FOREIGN KEY([RouteID], [ParentID])
REFERENCES [dbo].[ORUT] ([RouteID], [ParentID])
GO

ALTER TABLE [dbo].[RUT1] CHECK CONSTRAINT [FK_RUT1_ORUT]
GO


