ALTER TABLE OCLMP ADD CreatedIPAddress VARCHAR(15)
ALTER TABLE OCLMP ADD UpdateIPAddress VARCHAR(15)

ALTER TABLE OFGT ADD SAPCREATEDBY NVARCHAR(25)
ALTER TABLE OFGT ADD SAPCREATEDDATE DATETIME
ALTER TABLE OFGT ADD SAPCHANGEBY NVARCHAR(25)
ALTER TABLE OFGT ADD SAPCHANGEDATE DATETIME
ALTER TABLE OFGT ADD SAPSYNCUSER NVARCHAR(25)
Go
ALTER TABLE OEMP ADD IsAdmin BIT
GO
UPDATE OEMP SET IsAdmin =0
GO
ALTER TABLE OEMP ALTER COLUMN IsAdmin BIT NOT NULL
GO
ALTER TABLE OEMP ADD CONSTRAINT DF_IsAdmin DEFAULT 0 FOR IsAdmin;
GO
-------------------------
ALTER TABLE OSEQ ADD CreatedBy INT
GO
UPDATE OSEQ SET CreatedBy = 1
GO
ALTER TABLE OSEQ ALTER COLUMN CreatedBy INT NOT NULL
GO
ALTER TABLE OSEQ ADD UpdatedBy INT
ALTER TABLE OSEQ ADD UpdatedDate DATETIME
ALTER TABLE OSEQ ADD CreatedType INT
UPDATE OSEQ SET CreatedType = 2
update OSEQ set createdtype = 4 WHERE PARENTID IN ( SELECT CUSTOMERID FROM OCRD WHERE TYPE=4)

GO
ALTER TABLE OCLMRA ADD DocumentDate DATETIME NULL

UPDATE OMNU SET SortOrder=29, PARENTMENUID = 101, CMS = 1 WHERE  MENUID = 241

	ALTER TABLE OMID ADD DivisionID INT
	GO
	UPDATE A SET A.DivisionID = (Select Top 1 B.DivisionlID From OGITM B join MID1 C On B.ItemID = C.ItemID Where A.ParentID = C.ParentID And A.InwardId = C.InwardID )
	From OMID A WHERE A.DivisionID IS NULL
	GO
	UPDATE OMID SET DIVISIONID = 3 WHERE DivisionID IS NULL
	GO

ALTER TABLE PLT1 ADD CreatedDate DATETIME 
ALTER TABLE PLT1 ADD UpdatedDate DATETIME 
ALTER TABLE PLT1 ADD UpdatedBy INT
ALTER TABLE PLT1 ADD CreatedBy INT
GO
UPDATE PLT1 SET CreatedDate = GetDate()
UPDATE PLT1 SET UpdatedDate = GetDate()
UPDATE PLT1 SET CreatedBy = 1
UPDATE PLT1 SET UpdatedBy = 1
GO
ALTER TABLE PLT1 ALTER COLUMN CreatedDate DATETIME NULL
ALTER TABLE PLT1 ALTER COLUMN UpdatedDate DATETIME NULL
ALTER TABLE PLT1 ALTER COLUMN UpdatedBy INT NULL
ALTER TABLE PLT1 ALTER COLUMN CreatedBy INT NULL
GO
ALTER TABLE OGPS ADD Accuracy varchar(50)
ALTER TABLE OENT ADD InAccuracy varchar(50)
ALTER TABLE OENT ADD OutAccuracy varchar(50)
ALTER TABLE OCSE ADD InAccuracy varchar(50)
ALTER TABLE OCSE ADD OutAccuracy varchar(50)
GO
	ALTER TABLE OGPS ADD Distance DECIMAL(10,2)
	ALTER TABLE OCSE ADD InDistance DECIMAL(10,2)
	ALTER TABLE OENT ADD InDistance DECIMAL(10,2)
	ALTER TABLE OENT ADD OutDistance DECIMAL(10,2)
GO
	ALTER TABLE OCOMP ALTER COLUMN ContactPerson nvarchar(50)
	ALTER TABLE OCOMP ALTER COLUMN Location nvarchar(100)
GO
ALTER TABLE OIPL ADD Description nvarchar(500)

Update omnu set sortorder = 19 where menuid = 80
Update omnu set sortorder = 20 where menuid = 242

GO

ALter Table OPOS Add HDocID INT
GO
ALter Table OMID Add HDocID INT
GO
ALter Table ORET Add HDocID INT
GO
ALter Table ORDR Add HDocID INT

GO
ALter Table OEMP Add Institute nvarchar(100)
ALter Table OEMP Add Certificate nvarchar(50)
ALter Table OEMP Add HeadQuarter nvarchar(50)


ALter Table OEMP Add IsDMS BIT
GO
UPDATE OEMP SET IsDMS =1
GO
ALTER TABLE OEMP ALTER COLUMN IsDMS BIT NOT NULL 
GO
ALTER TABLE OEMP ADD CONSTRAINT DF_IsDMS DEFAULT 0 FOR IsDMS;
GO
ALTER TABLE SCM4 ADD Price MONEY NULL
GO
UPDATE SCM4 SET Price =0
GO
ALTER TABLE SCM4 ALTER COLUMN Price MONEY NOT NULL 
GO
ALTER TABLE SCM4 ADD CONSTRAINT DF_Price DEFAULT 0 FOR Price;
GO
ALTER TABLE POS3 ADD RateForScheme MONEY NULL
GO
ALTER TABLE OSCM ADD IsSAP BIT NULL
GO
Update OSCM set IsSAP = 1 where ApplicableMode = 'M' 
Update OSCM set IsSAP = 0 where ApplicableMode != 'M'
GO
ALTER TABLE OSCM ALTER COLUMN IsSAP BIT NOT NULL 
GO
-----------------------
ALTER TABLE OSCM ADD ForTemp BIT NULL
GO
UPDATE OSCM SET ForTemp = 0 
GO
ALTER TABLE OSCM ALTER COLUMN ForTemp BIT NOT NULL
GO
ALTER TABLE OSCM ADD ForFOW BIT NULL
GO
UPDATE OSCM SET ForFOW = 0 
GO
ALTER TABLE OSCM ALTER COLUMN ForFOW BIT NOT NULL
GO
ALTER TABLE OSCM ADD SchemeCondition INT NULL
GO
UPDATE OSCM SET SchemeCondition = 2
GO
ALTER TABLE OSCM ALTER COLUMN SchemeCondition INT NOT NULL
Go
ALTER TABLE OCFG ADD AvgPurchasePer INT NULL
GO
ALTER TABLE ENT1 ADD CallID INT NULL
GO
Alter Table OMSG Add ApplicableFromDate Datetime
GO 
Alter Table OMSG Add ApplicableToDate Datetime 
GO
ALTER TABLE OAWRK ADD EmpGrpID INT NULL
GO
ALTER TABLE OAWRK ADD MaxLimit numeric(18,2) NULL
GO
ALTER TABLE OAWRK ADD MinLimit numeric(18,2) NULL
GO
INSERT INTO OSET Values('deliverysyncmail','dmssupport@vadilalgroup.com,abhijit@vadilalgroup.com,jigneshkhajanchi@vadilalgroup.com')
GO
ALter Table OEMP Add HomeDistance Decimal(18,2)
GO
ALter Table OSMS Add ExcEmp nvarchar(300)
GO
ALTER TABLE OQUES ADD SortOrder INT NULL
GO
UPDATE OQUES SET SortOrder =0
GO
ALTER TABLE OQUES ALTER COLUMN SortOrder INT NOT NULL
GO
ALTER TABLE OEAS ADD StatusFilter varchar(50)
GO
UPDATE OEAS SET StatusFilter = 'E' WHERE AppStatusID IN (4)
UPDATE OEAS SET StatusFilter = 'E,MD' WHERE AppStatusID IN (1)
UPDATE OEAS SET StatusFilter = 'E,L,MD' WHERE AppStatusID IN (2,3)
GO
Insert into OEAS Values(5,'Query',0,0,null,GETDATE(),1,GETDATE(),1,1,'MD')
GO
Insert Into EEML values (10,1000010000000000,'Email for W/o Beat dealer Invoice',1,'06:30:00.0000000','exec [VDMS].[dbo].Get_HRY1ForEMail ''1000010000000000''','2099-02-26 06:30:16.637',GETDATE(),1,GETDATE(),1,1,0)
Insert Into EML1 values (10,1000010000000000,10,1,1,0)
GO
Alter Table OPOS Add ShippingID INT
GO
ALTER TABLE ORDR ADD CancelFlag varchar(5)
ALTER TABLE ORDR ADD CancelBy INT
ALTER TABLE ORDR ADD CancelDate DATETIME


Update  ORDR set CancelFlag='DIST',CancelBy=updatedBy,CancelDate= updatedDate where ORderType = '14'

ALTER TABLE OITM ADD GroupSortOrder INT
ALTER TABLE OITM ADD ItemSortOrder INT
Go
ALTER TABLE OENT ADD StartLocation varchar(250)
ALTER TABLE OENT ADD EndLocation varchar(250)
GO
ALTER TABLE OMID ADD InProcess BIT
GO
UPdate OMID set InProcess = 0 WHERE INwardType = 1
Go
ALTER TABLE OCSE ADD RouteID int
GO
Alter table CRD1 Alter Column Location nvarchar(100)
GO
ALTER TABLE OEMP ADD SAPActive BIT DEFAULT 0
GO
UPDATE OEMP SET SAPActive = 0
GO
ALTER TABLE OEMP ALTER COLUMN SAPActive BIT NOT NULL 
GO
Update OEMP set SAPActive = Active
GO
ALTER TABLE OGRP ADD SortOrder SMALLINT DEFAULT 999 NOT NULL
GO

ALTER TABLE OPOS ADD GSTIN varchar(20)

ALTER TABLE OCRD ADD CompetitorID INT

ALTER TABLE OCOMP ADD Accuracy varchar(50)
ALTER TABLE OCOMP ADD Distance DECIMAL(10,2)

ALTER TABLE OAST ADD AssetCapDate Date
GO
ALTER TABLE OENT ADD Location varchar(250)
GO
ALTER TABLE GCM1  ALTER COLUMN Title nvarchar(100)
GO
ALTER TABLE OSFB ADD PlantID INT
GO
ALTER TABLE OAST ADD PreventiveDays int
GO
ALTER TABLE OAST ADD MechanicEmpID int
GO
ALTER TABLE OAST ADD LastMaintainanceDate Date
GO
ALTER TABLE OEXT ADD GLCode NVARCHAR (10)
GO
ALTER TABLE OAST ADD PlannerName VARCHAR (10)
ALTER TABLE OAST ADD StorageLocID int
GO
ALTER TABLE AOCRD Add IPAddress varchar(20)
ALTER TABLE ACRD1 Add IPAddress varchar(20)
GO

/* Message Broadcast : Add image upload option */
ALTER TABLE dbo.OMSG
ADD ImageUpload varchar(500) NULL
GO

ALTER TABLE OCLMRQ
ADD CreatedIPAddress Varchar(15)
GO
ALTER TABLE OCLMRA
ADD CreatedIPAddress Varchar(15)
GO

ALTER TABLE ORUT 
ADD CreatedIpAddress varchar(15)
GO
ALTER TABLE ORUT 
ADD UpdatedIpAddress varchar(15)
GO

ALTER TABLE OCLMP
DROP COLUMN UpdateIPAddress
GO

--Dms/Pulse Authorization
ALTER TABLE GRP1 
ADD UpdatedDate DATETIME 
GO

ALTER TABLE GRP1
ADD UpdatedBy int
GO

ALTER TABLE GRP1 
ALTER COLUMN UPDATEDDATE DATETIME NOT NULL
GO

ALTER TABLE GRP1 
ALTER COLUMN UPDATEDBY INT NOT NULL
GO

alter TABLE [OSEQ]
add IsDeleted bit NOt Null default 0;
GO
Alter table OEMP add StartDay INT
GO
ALTER TABLE OCRD ADD BillToPartyCustID DECIMAL(18,0) NULL
GO
