SP_RENAME 'OCRD.ECCNumber', 'GSTIN', 'COLUMN'
GO
SP_RENAME 'OCRD.CSeqQuestion', 'CompositeScheme', 'COLUMN'
GO
ALTER TABLE OCRD ALTER COLUMN CompositeScheme BIT
GO
UPDATE OCRD SET CompositeScheme = 0
GO
ALTER TABLE OCRD ALTER COLUMN CompositeScheme BIT NOT NULL
GO
SP_RENAME 'OPLT.Address', 'GSTIN', 'COLUMN'
GO
ALTER TABLE OITM Add HSNCode nvarchar(50)
GO
Alter Table TOCRD Add SAPFlag Nvarchar(250)
GO
Alter Table TOCRD Add SAPMessage Nvarchar(250)
GO
ALTER TABLE OEMP ALTER COLUMN GCMID nvarchar(100)
GO
ALTER TABLE OEMP ADD GCM2ID nvarchar(100)
GO
ALTER TABLE OASTZ ADD AssetSubTypeID INT NOT NULL
GO
ALTER TABLE dbo.OASTZ ADD CONSTRAINT FK_OASTZ_OASTYB FOREIGN KEY ( AssetSubTypeID ) REFERENCES dbo.OASTYB ( AssetSubTypeID ) ON UPDATE NO ACTION ON DELETE NO ACTION
GO
ALTER TABLE OASTB ADD AssetSizeID INT NOT NULL
GO
ALTER TABLE dbo.OASTB ADD CONSTRAINT FK_OASTB_OASTZ FOREIGN KEY ( AssetSizeID ) REFERENCES dbo.OASTZ ( AssetSizeID ) ON UPDATE NO ACTION ON DELETE NO ACTION
GO
Alter Table TOCRD add Status int not null default(1)
GO
Alter Table OCFG add SAPGSTLink Nvarchar(MAX)
GO 
SP_RENAME 'OMID.Attachment', 'GSTInvNo', 'COLUMN'
GO
