Update OCST set GSTStateCode = '35' where StateName = 'Andaman and Nico.In.'
Update OCST set GSTStateCode = '28' where StateName = 'Andhra Pradesh'
Update OCST set GSTStateCode = '12' where StateName = 'Arunachal Pradesh'
Update OCST set GSTStateCode = '18' where StateName = 'Assam'
Update OCST set GSTStateCode = '10' where StateName = 'Bihar'
Update OCST set GSTStateCode = '4' where StateName = 'Chandigarh'
Update OCST set GSTStateCode = '22' where StateName = 'Chhattisgarh'
Update OCST set GSTStateCode = '26' where StateName = 'Dadra and Nagar Hav.'
Update OCST set GSTStateCode = '25' where StateName = 'Daman and Diu'
Update OCST set GSTStateCode = '7' where StateName = 'Delhi'
Update OCST set GSTStateCode = '0' where StateName = 'DoNotUse Uttaranchal'
Update OCST set GSTStateCode = '30' where StateName = 'Goa'
Update OCST set GSTStateCode = '24' where StateName = 'Gujarat'
Update OCST set GSTStateCode = '6' where StateName = 'Haryana'
Update OCST set GSTStateCode = '2' where StateName = 'Himachal Pradesh'
Update OCST set GSTStateCode = '1' where StateName = 'Jammu and Kashmir'
Update OCST set GSTStateCode = '20' where StateName = 'Jharkhand'
Update OCST set GSTStateCode = '29' where StateName = 'Karnataka'
Update OCST set GSTStateCode = '32' where StateName = 'Kerala'
Update OCST set GSTStateCode = '31' where StateName = 'Lakshadweep'
Update OCST set GSTStateCode = '23' where StateName = 'Madhya Pradesh'
Update OCST set GSTStateCode = '27' where StateName = 'Maharashtra'
Update OCST set GSTStateCode = '14' where StateName = 'Manipur'
Update OCST set GSTStateCode = '17' where StateName = 'Meghalaya'
Update OCST set GSTStateCode = '15' where StateName = 'Mizoram'
Update OCST set GSTStateCode = '13' where StateName = 'Nagaland'
Update OCST set GSTStateCode = '21' where StateName = 'Orissa'
Update OCST set GSTStateCode = '34' where StateName = 'Pondicherry'
Update OCST set GSTStateCode = '3' where StateName = 'Punjab'
Update OCST set GSTStateCode = '8' where StateName = 'Rajasthan'
Update OCST set GSTStateCode = '11' where StateName = 'Sikkim'
Update OCST set GSTStateCode = '33' where StateName = 'Tamilnadu'
Update OCST set GSTStateCode = '36' where StateName = 'Telangana'
Update OCST set GSTStateCode = '16' where StateName = 'Tripura'
Update OCST set GSTStateCode = '9' where StateName = 'Uttar Pradesh'
Update OCST set GSTStateCode = '5' where StateName = 'Uttarakhand'
Update OCST set GSTStateCode = '19' where StateName = 'West Bengal'
