ALTER TABLE OPOS ADD OrderRefID INT NULL
GO
ALTER TABLE ENT1 ADD CityName nvarchar(200) NULL
GO
ALTER TABLE ENT1 ADD Location nvarchar(200) NULL
GO
ALTER TABLE OEMP ADD IsSAP BIT NULL
GO
Update OEMP set IsSAP = 0
GO
ALTER TABLE OEMP ALTER COLUMN IsSAP BIT NOT NULL
GO
ALTER TABLE OEMP ADD CONSTRAINT DF_IsSAP DEFAULT 0 FOR IsSAP;
GO
ALTER TABLE ENT1 ALTER COLUMN Ref1 nvarchar(100) NULL
GO
ALTER TABLE ENT1 ALTER COLUMN Ref2 nvarchar(100) NULL
GO
ALTER TABLE ENT1 ALTER COLUMN Ref3 nvarchar(100) NULL
GO
ALTER TABLE ENT1 ALTER COLUMN Ref4 nvarchar(100) NULL
GO
ALTER TABLE ENT1 ALTER COLUMN Ref5 nvarchar(100) NULL
GO
ALTER TABLE OMID ADD PlantID INT 
GO
ALTER TABLE POS3 ADD AssetID INT
GO
Alter table pos1 Add PPrice money null
GO
ALTER TABLE RUT2 ADD AppDate DATETIME NULL
GO
ALTER TABLE OEMP ADD EmpGradeID INT NULL
Go
select T1.AssetID,t6.AssetID
--UPDATE T1 SET T1.AssetID = T6.AssetID
from OSCM T0
JOIN POS3 T1 ON T1.SchemeID = T0.SchemeID
JOIN OPOS T2 ON T1.SaleID = T2.SaleID AND T1.ParentID = T2.ParentID
LEFT OUTER JOIN SCM1 T6 ON T6.SchemeID = T0.SchemeID AND T6.CustomerID = T2.CustomerID
WHERE T0.ApplicableMOde= 'D' AND T1.AssetID IS NULL
GO
select T1.AssetID,t6.AssetID
--UPDATE T1 SET T1.AssetID = T6.AssetID
from OSCM T0
JOIN POS3 T1 ON T1.SchemeID = T0.SchemeID
JOIN OPOS T2 ON T1.SaleID = T2.SaleID AND T1.ParentID = T2.ParentID
LEFT OUTER JOIN SCM1 T6 ON T6.SchemeID = T0.SchemeID AND T6.CustomerID = T2.CustomerID
WHERE T0.ApplicableMOde= 'P' AND T1.AssetID IS NULL
Go
ALTER TABLE GCM1 ADD IsDeleted BIT NULL
GO
UPDATE GCM1 set IsDeleted = 0
GO
ALTER TABLE GCM1 ALTER COLUMN IsDeleted BIT NOT NULL
GO
ALTER TABLE OCLM ADD Total MONEY
GO
UPDATE OCLM SET TOtal= 0
GO
ALTER TABLE OCLM ALTER COLUMN Total MONEY NOT NULL
GO
ALTER TABLE OCLM ADD IsAuto BIT NULL
GO
UPDATE OCLM SET IsAuto =1
GO
ALTER TABLE OCLM ALTER COLUMN IsAuto BIT NOT NULL
GO
ALTER TABLE OCLM ALTER COLUMN CustomerID numeric(18,0) NULL
GO
ALTER TABLE OASTQ ADD Amount money NULL
GO
ALTER TABLE OASTQ ADD LevelNo int NULL
GO
ALTER TABLE OASTQ ADD NextManagerID int NULL
GO
ALTER TABLE OASTQ ADD BudgeterID int NULL
GO
Alter table OEMP ADD IsApprover bit NULL
GO
UPDATE OEMP SET IsApprover = 0
GO
Alter table OEMP ALTER COLUMN IsApprover BIT NOT NULL
GO
Alter table OSMS ADD IsCustomer bit NOT NULL
GO
Alter table OSMS ADD Active bit NOT NULL
GO
